kind: pipeline
type: docker
name: default
steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 45.125.34.216
      username: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 4m
      script:
        - cd /www/wwwroot
        - >
          if [ -d ./naa ] && [ -f ./naa/package.json ]; then
            cd ./naa
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
              git pull origin main
          else
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
              git clone -q git@github.com:hexuntao/naa.git ./naa
            cd ./naa
          fi

        - pnpm install || true
        - pnpm build
        - pm2 restart ecosystem.config.js && pm2 save
