kind: pipeline
type: docker
name: default
steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 45.125.34.216
      username: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      script:
        - cd /www/wwwroot
        - '[ -d ./naa ] && rm -rf ./naa'
        # 这一行很重要，因为没有的话，第一次克隆就会失败
        - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone -q git@github.com:hexuntao/naa.git ./naa
        - cd naa
        - 'pnpm i && pnpm build && pm2 restart ecosystem.config.js && pm2 save'
