// Do not manually change, generated by @/modules/mybatis
// @ts-nocheck
/* eslint-disable */
/* prettier-ignore */
declare module '@/modules/mybatis' {
  interface MybatisMapper {
    'gen.gen.mapper': 'selectDbTableList' | 'selectDbTableListByNames' | 'selectDbTableColumnsByName'
  }
}

export {}
